TRUTH = (
    "Have you ever ghosted someone?"
    "Did you ever walk over your parents doing 'that'?",
    "Who was the last person you liked the most? Why?",
    "Have you ever been suspended from school?",
    "If you had to choose between being naked or having your thoughts popping in a thought bubble above your head for all to read, which would you choose?",
    "What's one thing you're afraid to lose?"
    "Do you like someone right now?",
    "One thing about your best friend that makes you jealous?",
    "Are you going to cheat on your boyfriend for a rich guy?",
    "What's your biggest turn?",
    "When was the last time you lied to your parents and why?",
    "Describe your ideal partner.",
    "What's the scariest thing you've ever done?"
    "Have you ever picked your nose and eaten it?",
    "When was the last time you lied to your parents and why?",
    "Have you ever lied about your age to participate in a contest?",
    "Have you ever been caught checking someone?",
  
)

DARE = (
    "Show the most embarrassing photos on your phone"
    "Show the last five people you texted and what their messages were",
    "Let a whole group DM someone from your Instagram account",
    "Eat raw garlic",
    "Do 100 squats",
    "Keep three ice cubes in your mouth until it melts",
    "Say something dirty to the person on your left. You have friends!",
    "Give a foot massage to the person on your right",
    "Put 10 different available liquids into a cup and drink it",
    "* Say the first word that comes to your mind",
    "Give a lap dance to someone of your choice",
    "Take off four pieces of clothing",
    "Like the first 15 posts on your Facebook newsfeed",
    "Eat a spoonful of mustard",
    "Close your eyes until you leave again",
    "Send sext to the last person in your phonebook",
    "Show off your orgasmic face",
    "Eat bananas seductively",
    "Empty your wallet/wallet and show everyone what's in it",
    "Do your best sexy crawl",
    "Pretend to be the person on your right for 10 minutes",
    "Eat a snack without using your hands",
    "Say two honest things about everyone in the group",
    "Twerk for a bit",
    "Try to make the group laugh as quickly as possible",
    "Try to put your whole fist in your mouth",
    "Tell everyone a shameful story about yourself",
    "Try to lick your elbow",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Tell me the saddest story you know",
    "Howling like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with imaginary poles",
    "Let other people tickle you and try not to laugh"
    "Put snacks in your mouth at once as much as you can",
    "Submit your latest selfie.",
    "Send your ugliest selfie.",
    "Send screenshot of your facebook search history",
    "Send a screenshot of your gallery.",
    "Send screenshot of your messenger inbox",
    "Say something very intimate.",
    "Send a screenshot of your twitter inbox",
    "Send a screenshot of your home screen.",
    "Send a cover of your favorite song.",
    "Do a lyric joke on someone and send the proof.",
    "Acknowledge your current crush. ❤️",
    "Tell me who your true love is.",
    "Send a screenshot of your gallery.",
    "Make your crush's photo as your dp.",
    "Suggest me to be bolder.",
)
